# Generated by Django 4.1.1 on 2023-12-09 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokedex', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemon',
            name='height',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pokemon',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='pokemon',
            name='pokemonId',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pokemon',
            name='sprite',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='pokemon',
            name='type1',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='pokemon',
            name='type2',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='pokemon',
            name='weight',
            field=models.IntegerField(default=0),
        ),
    ]
