# Generated by Django 5.0 on 2023-12-19 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokedex', '0003_pokemon_attack_pokemon_defense_pokemon_hp_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pokemon_team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pokemon1', models.IntegerField(default=0)),
                ('pokemon2', models.IntegerField(default=0)),
                ('pokemon3', models.IntegerField(default=0)),
                ('pokemon4', models.IntegerField(default=0)),
                ('pokemon5', models.IntegerField(default=0)),
                ('pokemon6', models.IntegerField(default=0)),
            ],
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='height',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='weight',
            field=models.FloatField(default=0),
        ),
    ]
