# Generated by Django 5.0 on 2023-12-19 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokedex', '0004_pokemon_team_alter_pokemon_height_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Combat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pokemonHp1', models.IntegerField(default=0)),
                ('pokemonHp2', models.IntegerField(default=0)),
                ('pokemonHp3', models.IntegerField(default=0)),
                ('pokemonHp4', models.IntegerField(default=0)),
                ('pokemonHp5', models.IntegerField(default=0)),
                ('pokemonHp6', models.IntegerField(default=0)),
                ('pokemonIAHp1', models.IntegerField(default=0)),
                ('pokemonIAHp2', models.IntegerField(default=0)),
                ('pokemonIAHp3', models.IntegerField(default=0)),
                ('pokemonIAHp4', models.IntegerField(default=0)),
                ('pokemonIAHp5', models.IntegerField(default=0)),
                ('pokemonIAHp6', models.IntegerField(default=0)),
            ],
        ),
    ]
