# Generated by Django 5.0 on 2023-12-19 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokedex', '0005_combat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemon_team',
            name='pokemon1',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='pokemon_team',
            name='pokemon2',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='pokemon_team',
            name='pokemon3',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='pokemon_team',
            name='pokemon4',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='pokemon_team',
            name='pokemon5',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='pokemon_team',
            name='pokemon6',
            field=models.IntegerField(default=1),
        ),
    ]
