# Generated by Django 5.0 on 2023-12-27 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokedex', '0006_alter_pokemon_team_pokemon1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='combat',
            name='pokemonIAId1',
            field=models.IntegerField(default=43),
        ),
        migrations.AddField(
            model_name='combat',
            name='pokemonIAId2',
            field=models.IntegerField(default=107),
        ),
        migrations.AddField(
            model_name='combat',
            name='pokemonIAId3',
            field=models.IntegerField(default=31),
        ),
        migrations.AddField(
            model_name='combat',
            name='pokemonIAId4',
            field=models.IntegerField(default=68),
        ),
        migrations.AddField(
            model_name='combat',
            name='pokemonIAId5',
            field=models.IntegerField(default=47),
        ),
        migrations.AddField(
            model_name='combat',
            name='pokemonIAId6',
            field=models.IntegerField(default=7),
        ),
    ]
