# Generated by Django 5.0 on 2024-01-11 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokedex', '0007_combat_pokemoniaid1_combat_pokemoniaid2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='combat',
            name='pokemonIAId1',
            field=models.IntegerField(default=14),
        ),
        migrations.AlterField(
            model_name='combat',
            name='pokemonIAId2',
            field=models.IntegerField(default=69),
        ),
        migrations.AlterField(
            model_name='combat',
            name='pokemonIAId3',
            field=models.IntegerField(default=35),
        ),
        migrations.AlterField(
            model_name='combat',
            name='pokemonIAId4',
            field=models.IntegerField(default=77),
        ),
        migrations.AlterField(
            model_name='combat',
            name='pokemonIAId5',
            field=models.IntegerField(default=119),
        ),
        migrations.AlterField(
            model_name='combat',
            name='pokemonIAId6',
            field=models.IntegerField(default=88),
        ),
    ]
